name: add comment on issue
on: 
 pull_request:
 issues:

permissions:
 issues: read
 
env:
 GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
jobs:
 comment_issue:
  name: comment-issue-job
  runs-on: ubuntu-latest
  steps: 
  - uses: actions/checkout@v3
  - name: create a comment with git cli
    run: |
      gh issue comment ${{ github.event.issue.number }} --body "This is my test comment created with a workflow using github cli"
