name: add comment on issue
on: 
 pull_request:
 issues:

jobs:
 comment_issue:
  name: comment-issue-job
  runs-on: ubuntu-latest
  steps: 
  - uses: actions/checkout@v3
  - name: create a comment with git cli
    run: |
      gh issue comment ${{ github.event.issue.number }} --body "Hello from the GitHub workflow"
